name: car_juggle_photo_app
description: Car juggle photo app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  device_info: 2.0.2
  package_info: 2.0.2
  sentry: 5.1.0
  get_storage: 2.0.3
  connectivity: 3.0.6
  dio: 4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: 5.0.0+2
  get: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700